[package]
name = "bincode_ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "bincode_ffi"
crate-type = ["staticlib", "cdylib"]

[dependencies]
bincode = "1.3.3"
triton-vm = { path = "../../triton-vm-1.0.0/triton-vm", default-features = false }
getrandom = "0.2"
serde_json = "1"
anyhow = "1"

